// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQTb-94Ezx9TKwlOpp1KZHuFfGZRd-VVs',
    appId: '1:552605622755:web:0ac893af41eaad029780d6',
    messagingSenderId: '552605622755',
    projectId: 'aawaj-52af1',
    authDomain: 'aawaj-52af1.firebaseapp.com',
    storageBucket: 'aawaj-52af1.firebasestorage.app',
    measurementId: 'G-VPQMZ3SKX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCE_wtj0GL0FB8ipFFAMWry0RQh1tklqs',
    appId: '1:552605622755:android:bcc20d97f18992d39780d6',
    messagingSenderId: '552605622755',
    projectId: 'aawaj-52af1',
    storageBucket: 'aawaj-52af1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKdeHOaw7NvtT10o8wLGf_4zOkN1vxKoo',
    appId: '1:552605622755:ios:4e5f56bb0b9d36df9780d6',
    messagingSenderId: '552605622755',
    projectId: 'aawaj-52af1',
    storageBucket: 'aawaj-52af1.firebasestorage.app',
    iosBundleId: 'com.eagle.eye.avaz.eagleEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKdeHOaw7NvtT10o8wLGf_4zOkN1vxKoo',
    appId: '1:552605622755:ios:4e5f56bb0b9d36df9780d6',
    messagingSenderId: '552605622755',
    projectId: 'aawaj-52af1',
    storageBucket: 'aawaj-52af1.firebasestorage.app',
    iosBundleId: 'com.eagle.eye.avaz.eagleEye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQTb-94Ezx9TKwlOpp1KZHuFfGZRd-VVs',
    appId: '1:552605622755:web:856d2964dbf73e549780d6',
    messagingSenderId: '552605622755',
    projectId: 'aawaj-52af1',
    authDomain: 'aawaj-52af1.firebaseapp.com',
    storageBucket: 'aawaj-52af1.firebasestorage.app',
    measurementId: 'G-8E1MKLWW3N',
  );
}
