// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCI8n08uzrsk_4L7-ipvaa4y7PLJzuj89k",
      authDomain: "eagle-eye-oprator.firebaseapp.com",
      projectId: "eagle-eye-oprator",
      storageBucket: "eagle-eye-oprator.firebasestorage.app",
      messagingSenderId: "1086312563652",
      appId: "1:1086312563652:web:090170d09ceceeb0b15a91",
      measurementId: "G-WTRVEYKMG1"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUVqUmqNKouTQmUJp2swhy0-VSqj-2g2k',
    appId: '1:1086312563652:android:9deee97e2ecf4c81b15a91',
    messagingSenderId: '1086312563652',
    projectId: 'eagle-eye-oprator',
    storageBucket: 'eagle-eye-oprator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClFuAibcd035ejKDsoGH4t7T3thrYb8SY',
    appId: '1:1086312563652:ios:92a11174e0ab616cb15a91',
    messagingSenderId: '1086312563652',
    projectId: 'eagle-eye-oprator',
    storageBucket: 'eagle-eye-oprator.firebasestorage.app',
    iosBundleId: 'com.example.eagleEyeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClFuAibcd035ejKDsoGH4t7T3thrYb8SY',
    appId: '1:1086312563652:ios:92a11174e0ab616cb15a91',
    messagingSenderId: '1086312563652',
    projectId: 'eagle-eye-oprator',
    storageBucket: 'eagle-eye-oprator.firebasestorage.app',
    iosBundleId: 'com.example.eagleEyeAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI8n08uzrsk_4L7-ipvaa4y7PLJzuj89k',
    appId: '1:1086312563652:web:c5c1932e7ee0ef95b15a91',
    messagingSenderId: '1086312563652',
    projectId: 'eagle-eye-oprator',
    authDomain: 'eagle-eye-oprator.firebaseapp.com',
    storageBucket: 'eagle-eye-oprator.firebasestorage.app',
    measurementId: 'G-WHCPB3PXBM',
  );
}
